version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    container_name: petstore-django
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev
    ports:
      - "8000:8000"
    restart: on-failure
    command: /start

  postgres:
    container_name: petstore-database
    image: postgres
    env_file:
      - .envs/.dev
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
