# Generated by Django 2.2.6 on 2020-02-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Pet Name')),
                ('status', models.CharField(choices=[('0', 'available'), ('1', 'pending'), ('2', 'sold')], default='0', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
