# Generated by Django 2.2.6 on 2020-02-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tag',
            field=models.ManyToManyField(related_name='pet_tags', to='tag.Tag'),
        ),
    ]
