# Generated by Django 2.2.6 on 2020-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photoUrl',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
