# Generated by Django 2.2.6 on 2020-02-09 11:17

from django.db import migrations, models
import pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
