# Generated by Django 2.2.6 on 2020-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20200209_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
