#!/bin/bash

set -e

# the official postgres image uses 'postgres' as default user if not set explicitly.
if [[ -z "$POSTGRES_USER" ]]; then
    export POSTGRES_USER=postgres
    export POSTGRES_DB=postgres
fi

function postgres_ready(){
python << END
import sys
import psycopg2
try:
    conn = psycopg2.connect(dbname="${POSTGRES_DB}", user="${POSTGRES_USER}", password="${POSTGRES_PASSWORD}", host="${POSTGRES_HOST}")
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
  >&2 echo "Postgres unavailable - Sleeping..."
  sleep 1
done

if [[ $# -ge 1 ]]; then
    exec "$@"
fi